apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: presentations
spec:
  clusterName: infinispan
  name: presentations
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: "1"
      statistics: "true"
      encoding:
        mediaType: "application/x-protostream"
      persistence:
        fileStore: ~
      expiration:
        lifespan: "3600000"  # Tempo de vida do cache em milissegundos (1h)
      memory:
        maxSize: "500MB" 